version: "3.8"

# Docker-compose file to run a nimbus beacon node.

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.

services:
  nimbus:
    image: statusim/nimbus-eth2:amd64-${NUMBUS_VERSION:-v22.10.0}
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${NIMBUS_PORT_P2P:-9001}:9001/tcp   # P2P TCP
      - ${NIMBUS_PORT_P2P:-9001}:9001/udp   # P2P UDP
      - ${NIMBUS_PORT_REST:-5053}:5053/tcp  # Beacon REST API
    volumes:
      - ./data/nimbus:/home/user/nimbus-eth2/build/data
    # Ensure port 9001 is accessible from outside; no automagic port forwarding here
    command: |
      ${NIMBUS_TRUSTED_SYNC:-}
      --network=prater
      --data-dir=/home/user/nimbus-eth2/build/data/shared_prater_0
      --web3-url=${NIMBUS_WEB3_URL:-http://geth:8551}
      --nat=extip:${NIMBUS_EXTERNAL_IP:-127.0.0.1}
      --log-level=info
      --tcp-port=9001
      --udp-port=9001
      --rest
      --rest-address=0.0.0.0
      --rest-port=5053
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=8008

networks:
  default:
    name: ${NIMBUS_DOCKER_NETWORK:-charon-distributed-validator-node_dvnode}
    external: true